/*
 * This source file was generated by the Gradle 'init' task
 */
package uno.usagi.numtext;

import java.util.Scanner;

public class App {
static Scanner scanner = new Scanner(System.in);

public static String getFullUserInput(int userInput){
    String result = "";
    int billions = userInput/1000000000;
    int millions = (userInput/1000000) % 1000;
    int thousands = (userInput/1000) % 1000;
    int units = userInput % 1000;
    if(userInput == 0) {
        return "zero";
    }

    if(billions > 0){
        result += getThreeDigits(billions) + " billion";
    }

    if(millions > 0){
        if(result.length() > 0){
            result += " ";
        }
        result += getThreeDigits(millions) + " million";
    }

    if(thousands > 0){
        if(result.length() > 0){
            result += " ";
        }
        result += getThreeDigits(thousands) + " thousand";
    }

    if(units > 0){
        if(result.length() > 0){
            result += " ";
        }
        result += getThreeDigits(units);
    }
    return result;
}
    public static void main(String[] args) {
        System.out.print("Please enter a number between 0 and 2,147,483,647 >> ");
        
        // ^ Goes OUTSIDE the loop to avoid repeated printing with invalid number message (only prints ONCE, at the start of the program)

        while(true){
            
        try {
            
            int numberToTextify = Integer.parseInt(scanner.nextLine());
            
            System.out.println("you chose " + numberToTextify);
            System.out.println(getFullUserInput(numberToTextify));
            // ^test code
            break;
        } catch (NumberFormatException e) {
            System.out.print("Please enter a valid number between 0 and 2,147,483,647 >> ");
            // ^ Goes INSIDE the loop to repeatedly prompt the user (once per invalid input) to enter a valid number
        }
        
    }
}
    public static String getThreeDigits(int numberToTextify){    
        //we need to call in getsingledigit, gettens, getirregulars
        int ones = numberToTextify % 10;
        int tens = (numberToTextify / 10) % 10;
        int hundreds = (numberToTextify / 100) % 10;
        String result = "";

        if(hundreds > 0){
            result += getSingleDigit(hundreds) + " hundred";
        }
        
        if(tens == 1){
            if(result.length() > 0){
                result += " ";
            }
            result += getIrregulars(ones);
        } else if(tens >= 2){
            if(result.length() > 0){
                result += " ";
            }
            result += getTens(tens);
        }
        if(tens != 1 && ones != 0){
            if(result.length() > 0){
                result += " ";
            }
            result += getSingleDigit(ones);
        }


        return result;
    }
    public static String getSingleDigit(int digit){
        if(digit == 1){
            return "one";

        } else if(digit == 2){
            return "two";

        } else if(digit == 3){
            return "three";

        } else if(digit == 4){
            return "four";

        } else if(digit == 5){
            return "five";

        } else if(digit == 6){
            return "six";

        } else if(digit == 7){
            return "seven";

        }else if(digit == 8){
            return "eight";

        } else if(digit == 9){
            return "nine";

        } else {
            return null;

        }

    }
    public static String getTens(int tens){
        if(tens == 2){
            return "twenty";
        } else if(tens == 3){
            return "thirty";
        
        } else if(tens == 4){
            return "fourty";
        
        } else if(tens == 5){
            return "fifty";
        
        } else if(tens == 6){
            return "sixty";
        
        } else if(tens == 7){
            return "seventy";
        
        } else if(tens == 8){
            return "eighty";
        
        } else if(tens == 9){
            return "ninety";

        } else {
            return null;
        }
    }
    public static String getIrregulars(int irregular){
        if(irregular == 1){
            return "eleven";

        } else if(irregular == 2){
            return "twelve";

        } else if(irregular == 3){
            return "thirteen";

        } else if(irregular == 4){
            return "fourteen";

        } else if(irregular == 5){
            return "fifteen";
        
        } else if(irregular == 6){
            return "sixteen";
        
        } else if(irregular == 7){
            return "seventeen";

        } else if(irregular == 8){
            return "eighteen";
        
        } else if(irregular == 9){
            return "nineteen";

        } else {
            return null;
        }
    }
}